### ISSUE TITLE
Publish - blocking issues

### ISSUE THREAD

**Issue by kptdobe** [adobe/developer.adobe.com#104]
Since I am a bit lost with the number of issues regarding publishing the site, I propose to maintain here a list of the blocking issues:

* ~~/launch/docs returns 404: https://github.com/adobe/developer.adobe.com/issues/105~~
* ~Missing SVG icons:~ https://github.com/adobe/developer.adobe.com/issues/88
* ~~Weird error message on `hlx deploy`: https://github.com/adobe/developer.adobe.com/issues/103~~
* ~~Fix the nav links: https://github.com/adobe/developer.adobe.com/issues/82~~
* ~Deploy (via circleci) yields errors:~ https://github.com/adobe/developer.adobe.com/issues/92
* ~Random / intermittent static asset HTTP 50x errors (needs verification / reproduction)~ https://github.com/adobe/developer.adobe.com/issues/58
* ~The first hit to the site after publishing yields HTTP 500 (needs verification / reproduction)~ https://github.com/adobe/developer.adobe.com/issues/59
* ~Techblog articles display on homepage when running locally, but not on deployed site~ #111

On a side note:
No issue yet but YOU MUST RUN `npm install` before running `hlx deploy` (you need to remember that). Otherwise the external dependencies are missing.

cc @rofe @tripodsan @trieloff @filmaj @stevengill

**Comment by tripodsan** [comment]
> No issue yet but YOU MUST RUN `npm install` before running `hlx deploy` (you need to remember that). Otherwise the external dependencies are missing.

this is kind of obvious, not?

**Comment by kptdobe** [comment]
Yes but so easy to forget...

**Comment by filmaj** [comment]
I added #92 as well

**Comment by filmaj** [comment]
Also added #58 and #59

**Comment by filmaj** [comment]
Added #111

**Comment by filmaj** [comment]
I think we've tackled them all in here!
