### ISSUE TITLE
/launch/docs is not accessible on publish site

### ISSUE THREAD

**Issue by kptdobe** [adobe/developer.adobe.com#105]
Try to reach https://alex.helix-demo.xyz/launch/docs, returns 404. The strain resolution magic does not seem to work on publish.

**Comment by kptdobe** [comment]
It ends up on the static action, no clue why: "x-action-root: /api/v1/web/acapt/default/hlx--static"

**Comment by kptdobe** [comment]
`req.url.dirname == '/launch'` and not `/launch/docs`, that's why the strain is not considered! Will open corresponding issue in the helix-cli. 
`xd` but with homepage content. There is more than that broken.

**Comment by filmaj** [comment]
Awesome! Thanks for dealing with that.

**Comment by stevengill** [comment]
Great work @kptdobe! Nice to see it all working on publish!

**Comment by filmaj** [comment]
Reopening, we should wait until this fix gets published in helix, and then we should also add helix-cli to the dependency list of this project so that we can lock down helix version as well.

**Comment by filmaj** [comment]
So I tried deploying w/ latest master of helix cli and it is not working for me :/

https://adobedevsite.helix-demo.xyz/ works fine. https://adobedevsite.helix-demo.xyz/launch/docs returns a 404. interestingly, if you add a trailing slash to that https://adobedevsite.helix-demo.xyz/launch/docs/ then you got a 400 with some stringified buffer data!

**Comment by filmaj** [comment]
Fixed!
