### ISSUE TITLE
Add nesting to side nav in docs template

### ISSUE THREAD

**Issue by stevengill** [adobe/developer.adobe.com#108]
Right now our side nav for docs is kinda weird. We should support at least three levels of nesting and make sure it looks the same for the various different summary.md files we are working with. This includes [XD](https://github.com/AdobeXD/plugin-docs/blob/master/SUMMARY.md), [launch](https://github.com/Adobe-Marketing-Cloud/reactor-user-docs/blob/master/SUMMARY.md), and [starter-docs](https://github.com/AdobeDocs/starter-docs/blob/master/SUMMARY.md)

**Comment by filmaj** [comment]
Going to move ahead assuming nested lists should render in a nested, spectrum-friendly way, and that two hashes signify a heading.
