### ISSUE TITLE
Update homepage content

### ISSUE THREAD

**Issue by simonwex** [adobe/developer.adobe.com#117]
https://docs.google.com/document/d/1YsIg9nQZDuHASzhNPh1yNEOwvgez2Na_PxejPAQTyQA/edit

**Comment by filmaj** [comment]
Is this content still supposed to use the mockups we've been using to dev against?

mobile: https://xd.adobe.com/spec/9a251811-9257-4493-5141-62a780c725ad-ec14/screen/74c4a0b8-8a98-47ca-9658-eef1d27fd8ae/Developer-Home-Mobile/
desktop: https://xd.adobe.com/spec/9a251811-9257-4493-5141-62a780c725ad-ec14/screen/c1d5e415-fd39-43dd-bb2e-5ae708c762dc/Developer-Home/

**Comment by simonwex** [comment]
That was the original goal, though I think they've walked away from each other quite a bit.

@britburger @jenlgray I know you've both been into both of these documents heavily. Do you have any thoughts on how to proceed?

**Comment by britburger** [comment]
@jenlgray, Erin and I reviewed the designs together last week and had a great conversation around the current state of the homepage and how close it was to the mark in terms of pairing down the marketing copy and prioritizing links out to the popular and active channels of communication. Takeaways were:

1. Remove the events module or replace it with a placeholder. I wondered afterwards about "Submit your event"?
2. Add more ways to get people to the blog other than through posts - this could be links out to post categories.

The content doc also adds some great  "Latest in Open Source" copy that I'd like to design a new content block for - although I believe we're still waiting for confirmation on whether we can use a quote touting the benefits of spectrum.

We're also waiting for design feedback from Shawn and the brand team on the comps. So the designs are currently unchanged but this new copy along with a revised UX for global navigation (@stevengill sorry I've not chimed in on this issue) may require an updated comp.

**Comment by filmaj** [comment]
FYI If we're gonna turf the events part of the homepage design then we can close #86.

**Comment by filmaj** [comment]
This issue also impacts work we want to accomplish in the current sprint (#126) so it would be good to understand if what was discussed in here is still in flux or if it is settled and we can move forward.

**Comment by filmaj** [comment]
I'm going to close this in favour of tracking everything here in #126.
