### ISSUE TITLE
New IA testing plan

### ISSUE THREAD

**Issue by kgera** [adobe/developer.adobe.com#132]
Need to plan testing for new IA across devices before making it live

**Comment by filmaj** [comment]
@kgera Is this related to the task/meeting we were supposed to have last week at Tech Summit but fell through?

**Comment by filmaj** [comment]
This may be related to #44

**Comment by kgera** [comment]
That is correct @filmaj  do you want me to close this issue and track the old one only?

**Comment by kgera** [comment]
Yes @filmaj, i was also thinking if you want to talk about it in this sprint's task.

**Comment by filmaj** [comment]
@kgera if there is 100% overlap, then yes I say we close this duplicate issue and focus our updates in just one issue, to make things simple 😄

**Comment by filmaj** [comment]
Closing in favour of #44.
