### ISSUE TITLE
Helix Support Process for Developer Website 

### ISSUE THREAD

**Issue by kgera** [adobe/developer.adobe.com#141]
Develop a support process for developer website when in production on situations like downtime, deployment issues. Who will support? Whom to reach out in case of any deployment on helix that affects the website? If we have latest helix version on master then what happens if any deployment in master impacts the production? Any maintenance activities? Plan for alerts setup for monitoring, etc.

**Comment by filmaj** [comment]
Closing as a duplicate. We have #128 (operation support for helix & fastly) and #134 (monitoring uptime).
