### ISSUE TITLE
Mobile first CSS

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/developer.adobe.com#23]
I just stumbled over some portions of the css that seemed to treat mobile as the special case.

I propose that we think of mobile as the *general* case and have desktop screen resolutions be the special case in media queries.

As for breakpoints (I already found 2 different breakpoints) I subscribe to https://medium.freecodecamp.org/the-100-correct-way-to-do-css-breakpoints-88d6a5ba1862 but i think it is something we could discuss

**Comment by filmaj** [comment]
Can confirm that development has been focusing on the mobile case first - almost to the detriment of the desktop case 🙈

**Comment by filmaj** [comment]
I think mobile-first is enshrined in our approach when developing the site so going to close this issue down as I think we've settled the issue.
