### ISSUE TITLE
Hackathon: Markdown extensions for Docs

### ISSUE THREAD

**Issue by simonwex** [adobe/developer.adobe.com#33]
> "The overriding design goal for Markdown’s formatting syntax is to make it as readable as possible," writes John Gruber of Daring Fireball, creator of Markdown. "The idea is that a Markdown-formatted document should be publishable as-is, as plain text, without looking like it’s been marked up with tags or formatting instructions."

It is important that we keep the Markdown syntax as close to GFM as possible. This is to maintain the benefits of Markdown itself. Some teams have already extended it to provide for things like l10n and magic like notice blocks.

![Example from Audience Manager Docs](https://user-images.githubusercontent.com/25260/48874222-faa0db00-eda6-11e8-8325-ffcfe07b7198.png)

[Example from Audience Manager Docs]
(https://git.corp.adobe.com/AdobeDocs/audience-manager.en/blob/master/help/using/reporting/general-reports.md)

It's tough to argue with the requirement for these additions, but we should think deeply about what we should set as the standard for all following teams. We want authoring to be a clean, sane and enjoyable experience for all authors including non-technical.

**Comment by filmaj** [comment]
I breached this topic again with the helix team this week and @davidnuescheler was pretty adamant that they want to stay away from this.

We have found ways to get around this (injecting markup / js / css in the pipeline instead). Going to close this down.
