### ISSUE TITLE
Present Synthesis deck to stakeholders

### ISSUE THREAD

**Issue by simonwex** [adobe/developer.adobe.com#42]
As part of wrapping up this phase, it'd be good to present our findings to our stakeholders.

**Comment by filmaj** [comment]
@wex is this still to be done or can we close?

**Comment by filmaj** [comment]
@simonwex is this still to be done or can we close?

**Comment by cmgeorge16** [comment]
The overall research synthesis deck that Adobe Design Dev Ecosystem team created was sent out to internal stakeholders last month. This was a deck that went across the work we're doing for the Developer Console + Website. Not only did it summarize the ecosystem and the themes presented throughout the interviews, but it also framed how in the future our teams would be reaching out to stakeholders individually depending on the needs of the project. This then gives the Website + Console teams flexibility to reach out as necessary for their particular project.

**Comment by filmaj** [comment]
In that case @simonwex @cmgeorge16 can we close this issue?

**Comment by filmaj** [comment]
Going to close this, feel free to re-open if that is applicable here.
