### ISSUE TITLE
Current site must specify file names + extensions

### ISSUE THREAD

**Issue by filmaj** [adobe/developer.adobe.com#56]
Pretty sure this is a helix bug, but I'm not sure where that bug is being tracked!

**Comment by kptdobe** [comment]
I do not understand the pb :)

**Comment by filmaj** [comment]
The `directoryIndex` config property does not seem to work - I _must_ specify the filename+ending, e.g. https://stage-developer.helix-demo.xyz/README.html vs. just https://stage-developer.helix-demo.xyz/

**Comment by filmaj** [comment]
actually... it does work... kind of? I swear this didn't work last night...

**Comment by filmaj** [comment]
Hmm, maybe the 'sub-strain' sections are where it doesn't work?

I.e. https://stage-developer.helix-demo.xyz/docs/launch vs. https://stage-developer.helix-demo.xyz/docs/launch/README.html

Based on [our helix config](https://github.com/adobe/Adobe-Developer-Site/blob/master/helix-config.yaml#L23)

**Comment by filmaj** [comment]
I don't think this is an issue anymore.
