### ISSUE TITLE
Helix static content sometimes yields random HTTP 500 responses

### ISSUE THREAD

**Issue by filmaj** [adobe/developer.adobe.com#58]
Seems like a helix bug. @trieloff said he wants to debug this with us 😇

**Comment by trieloff** [comment]
I've seen this too.

**Comment by filmaj** [comment]
Even on @kptdobe's latest published version of the site https://alex.helix-demo.xyz/ you can still see this problem. Interestingly, different static assets fail on each refresh.

**Comment by filmaj** [comment]
OK, but now it works. wtf???

**Comment by filmaj** [comment]
<img width="1428" alt="screen shot 2019-02-05 at 12 34 11 pm" src="https://user-images.githubusercontent.com/52645/52302535-5f99b500-2942-11e9-9762-3985a099ee6a.png">

Check it out, at 12:30PM local time it was failing on every refresh (in the screenshot only the last of these is shown, but there were several refreshes before then that had the same problem). Then @stevengill tried and he said "works for me" so I tried again, 2 minutes later at 12:32PM, and now it works.

wtf

**Comment by filmaj** [comment]
Havent' seen this for a bit, closing.
