### ISSUE TITLE
Post-deploy, first request to site is HTTP 500

### ISSUE THREAD

**Issue by filmaj** [adobe/developer.adobe.com#59]
May be related to #58, but yeah. Push to master. Wait for CI to complete. Load the site. womp womp.

**Comment by filmaj** [comment]
I also noticed this was the case after a "long" break in the site being loaded. Like, we stopped hacking today, went to eat/get drunk, then when I came back to hotel, tried loading the site (https://stage-developer.helix-demo.xyz/README.html), and got the same error as immediately after a fresh deploy.

**Comment by filmaj** [comment]
Interesting. Looks like this landed in helix-cli@0.10.6. I'll look to update helix in this repo and get a deploy out to see how things are different.

**Comment by trieloff** [comment]
Until we have adobe/helix-cli#408 in, I'd expect much more brokenness (you won't event get an error 500, just a silent, failing, 200)

**Comment by filmaj** [comment]
Thanks, good to know, I'll keep my eyes out for a fix for that landing and a relevant release being published before I try the fix(es) out.

**Comment by filmaj** [comment]
I cannot reproduce this anymore, so I'm closing.
