### ISSUE TITLE
Build intermediate top-level nav

### ISSUE THREAD

**Issue by simonwex** [adobe/developer.adobe.com#75]
Building on #72, let's build some stand-alone markup/css/js that can be used as top-level nav & header for both the helix and AEM versions of the site.

**Comment by filmaj** [comment]
We're talking about the top-nav in this screenshot, ya? 

![topnavscreenshot](https://user-images.githubusercontent.com/25260/50235156-1aa6c880-036c-11e9-9185-e8b1d5b925f6.png)

**Comment by stevengill** [comment]
I'm guessing we build this kinda like a web component so it could be used by either. The links in the nav would be hardcoded ya? Like we don't have to have them in a markdown file and render the nav from that.

**Comment by simonwex** [comment]
> We're talking about the top-nav in this screenshot, ya?
> 
@filmaj yes

**Comment by filmaj** [comment]
This has landed in master!
