### ISSUE TITLE
Replace font-awesome menu icon with spectrum showmenu icon

### ISSUE THREAD

**Issue by stevengill** [adobe/developer.adobe.com#83]
Couldn't get spectrum showmenu to work so I used font-awesome for now. Need to fix this.

**Comment by filmaj** [comment]
Yeah, I don't think the spectrum svg icons that ship with spectrum right now include the showmenu icon for some reason. i posed this question in the spectrum css channel.

**Comment by filmaj** [comment]
Latest commit on navs branch axes font-awesome and introduces full spectrum icons.
