### ISSUE TITLE
Where to pull "upcoming events" from?

### ISSUE THREAD

**Issue by filmaj** [adobe/developer.adobe.com#86]
The latest homepage mockup has a section on 'upcoming events':

<img width="288" alt="screen shot 2019-02-01 at 4 00 21 pm" src="https://user-images.githubusercontent.com/52645/52151997-81d9bd00-263a-11e9-99a3-7576ee5de7b7.png">

Question is: where does this data come from? @jenlgray are you aware of where I could get my hands on this kind of data? Ideally in a programmatic way so that I can script it into the site 😄

**Comment by stevengill** [comment]
Not having events on homepage for now
