### ISSUE TITLE
circleci borked

### ISSUE THREAD

**Issue by filmaj** [adobe/developer.adobe.com#92]
perhaps at this stage it's a bit early for running ci? maybe we turn it off for now? seems there are tests out there, though.

**Comment by kptdobe** [comment]
The CI tries to deploy automatically a new strain (on each commit...). Is this intended ? Maybe you can disable that for now.

The error message is weird:

```
#!/bin/bash -eo pipefail
npx hlx deploy --no-auto | cat && cat .hlx/strains.json
error: Remote repository ssh://git@github.com/adobe/developer.adobe.com.git#linting does not affect any strains.
      
Add a strain definition to your config file:
b27e78b0-f0f4-4429-994d-920ca959507e:
  code: ssh://git@github.com/adobe/developer.adobe.com.git#linting
  content: https://github.com/adobe/developer.adobe.com.git#master
  static: https://github.com/adobe/developer.adobe.com.git/htdocs#master
  package: 9e81a2d5d82f2a22bf218b446da32414f33c0d87


Alternatively you can auto-add one using the --add <name> option.

Exited with code 1
```

Maybe @tripodsan or @trieloff knows what is wrong.

**Comment by filmaj** [comment]
I'm trying to tackle this over in #99

**Comment by filmaj** [comment]
I got the CI working on that one PR (#99) - but then fails again on master (see https://circleci.com/gh/adobe/developer.adobe.com/147) with the 'unable to update params.vcl' error that we've seen intermittently on `publish`.

Maybe has something to do with `npx deploy --add master`? Maybe should not be using the `--add` flag when this runs on the master branch? I'm not sure....

**Comment by filmaj** [comment]
It randomly started working......

**Comment by filmaj** [comment]
Oooo we've hit a rate limit from fastly it looks like too!

```
error: - Set content repo429 - {"msg":"You have exceeded your hourly rate limit. Please contact support@fastly.com if you think this is a mistake."}
error: Error while running the Publish command: Error: Error setting edge dictionary value
    at job.putDict.then.catch (/home/circleci/project/node_modules/@adobe/helix-cli/src/publish.cmd.js:677:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)Error setting edge dictionary value
Error while running the Publish command
Exited with code 1
```

**Comment by kptdobe** [comment]
This https://github.com/adobe/helix-cli/issues/510 for the rate limit part of the issue.

**Comment by filmaj** [comment]
We've simplified CI, now just runs tests. Closing.
