### ISSUE TITLE
add linting

### ISSUE THREAD

**Issue by filmaj** [adobe/developer.adobe.com#94]
Lack of linting directive is really messing up my IDE haha. Let's add an `.eslintrc.js` file to the root of the repo to address this. Also funny as we have a bunch of eslint plugins and stuff in the dev dependencies already.

**Comment by kptdobe** [comment]
There is already one! My Visual Studio Code is already complaining with most of the files.
The task here would more be to apply linting everywhere! And maybe add the linting check as part of the CI.

**Comment by kptdobe** [comment]
I started a linting branch here: https://github.com/adobe/developer.adobe.com/tree/linting

**Comment by kptdobe** [comment]
ok, since I started, I will do it for you :)

**Comment by filmaj** [comment]
LOL you are too good to us 🙏

**Comment by filmaj** [comment]
Merged in in 6a6af88.
