### ISSUE TITLE
Why is loadIcons.js twice in the repo?

### ISSUE THREAD

**Issue by kptdobe** [adobe/developer.adobe.com#96]
https://github.com/adobe/developer.adobe.com/blob/master/htdocs/loadIcons.js
https://github.com/adobe/developer.adobe.com/blob/master/htdocs/icons/loadIcons.js

Any specific reason ?

**Comment by stevengill** [comment]
No reason. Probably just have it in html.htl and we are good

**Comment by filmaj** [comment]
none, we should axe it
